version: '3'

services:
  web:
    build: ./
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: always
  db:
    image: "postgres"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5433:5432"
